# 基础配置
site_name: 你的网站名
site_url: https://your-domain.com
site_author: 你的名字
site_description: 网站描述

# 主题配置
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    
# Google Analytics 和 AdSense 配置
extra_javascript:
  - assets/js/analytics.js
  - assets/js/adsense.js
