# 基础配置
site_name: 自洽的程序员
site_url: https://www.dev-life.site/
site_author: 辣条加辣
site_description: >-
  一本帮助程序员应对职场焦虑、倦怠、迷茫的指南。探讨程序员的工作哲学、方法论、人际关系和生活平衡。
docs_dir: docs
site_dir: site
use_directory_urls: true

# 主题配置
theme:
  name: material
  language: zh
  logo: assets/images/icon.png
  favicon: assets/images/favicon.png
  custom_dir: docs/overrides
  
  # 功能特性
  features:
    - navigation.footer
    - navigation.top        
    - navigation.tracking   
    - search.highlight     
    - content.code.copy    
    - content.action.download
    - content.action.view
    - content.action.edit
    - navigation.instant
    - search.share
    - search.suggest
    - content.tabs.link
  
  # 配色方案
  palette:
      # 深色模式
    - scheme: slate
      primary: blue grey   # 深色模式下的蓝灰色
      accent: grey        # 保持简约的灰色
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
    # 亮色模式
    - scheme: default
      primary: grey        # 优雅的灰色
      accent: blue grey    # 蓝灰色作为强调色
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    

  # 字体配置
  font:
    text: Roboto
    code: Roboto Mono
  
  # 图标配置
  icon:
    repo: fontawesome/brands/github
  repo_url: https://github.com/zhangchenchen/self-consistent-coder
  repo_name: self-consistent-coder
  edit_uri: edit/main/docs/

# 插件配置
plugins:
  - search    # 搜索插件
  # 本地开发时注释掉整个 with-pdf 插件配置
  # - with-pdf:
  #     author: 辣条加辣
  #     cover: true
  #     cover_title: 自洽的程序员
  #     cover_subtitle: 关于程序员职场和生活的思考
  #     toc_level: 2
  #     output_path: pdf/book.pdf
  #     stylesheets:
  #       - docs/stylesheets/pdf.css
  #     exclude_pages:
  #       - 'index.md'
  #     custom_template_path: docs/pdf_template
  #     debug_html: false
  #     show_anchors: false
  #     font_family: "WenQuanYi Micro Hei"
  #     language: zh
  #     compress: true
  #     encoding: UTF-8
  - mkdocs-simple-hooks:
      hooks:
        on_env: "docs.hooks:on_env"

# 扩展配置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zhangchenchen
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GeorgePekingzcc
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      我们使用 cookies 来识别您的重复访问和偏好，以及衡量我们文档的有效性和改进我们的网站。
  assets_version: '1.0'
  keywords: >-
    程序员,职场,焦虑,工作方法论,职业发展,程序员成长,工作与生活平衡,职场人际关系
  og_title: 自洽的程序员 - 程序员的职场生存指南
  og_description: 一本帮助程序员应对职场焦虑、倦怠、迷茫的指南
  og_image: assets/images/og-image.jpg
  og_type: website
  twitter_card: summary_large_image
  twitter_site: "@GeorgePekingzcc"
  twitter_creator: "@GeorgePekingzcc"
  sitemap:
    enabled: true
    url: https://www.dev-life.site/

# PWA 配置
pwa:
  enabled: true  
  name: 自洽的程序员  
  short_name: 自洽程序员  
  description: 关于程序员职场和生活的思考
  theme_color: "#2196f3"  
  background_color: "#ffffff"  
  icon:
    path: assets/images/icon.png  
  prefer_related_applications: false

# 资源文件
extra_javascript:
  - assets/js/analytics.js
  - assets/js/adsense.js

extra_css:
  - stylesheets/extra.css

# 版权信息
copyright: Copyright &copy; 2024 辣条加辣.

# 导航配置
nav:
    - 首页: index.md
    - 前言: preface/index.md
    - 第一章：建立你的工作哲学:
        - 概述: chapter1/index.md
        - 1.1 第一性原理思考工作: chapter1/section1.md
        - 1.2 工作挣扎是常态: chapter1/section2.md
        - 1.3 工作承载不了太多意义，但也不要陷入工作虚无主义: chapter1/section3.md
        - 1.4 人，要过得自私且坦荡: chapter1/section4.md
    - 第二章 工作方法论:
        - 概述: chapter2/index.md
        - 2.1 心态开放，你的职场第一课: chapter2/section1.md
        - 2.2 下场去做，你的职场第二课: chapter2/section2.md
        - 2.3 寻求帮助是项高级技能: chapter2/section3.md
        - 2.4 害怕直面冲突，怎样才能支棱起来: chapter2/section4.md
        - 2.5 如何面对职场PUA: chapter2/section5.md
        - 2.6 内耗，是从拒绝沟通开始的: chapter2/section6.md
        - 2.7 不喜欢编程，还要坚守程序员这个岗位吗: chapter2/section7.md
        - 2.8 工作倦怠了吗，试试三叶草模型: chapter2/section8.md
        - 2.9 天天用AI，以后自己不会写代码怎么办: chapter2/section9.md
        - 2.10 职场中如何做选择: chapter2/section10.md
        - 2.11 职场中最实用的三个思维模型: chapter2/section11.md
        - 2.12 不会吹牛逼，述职/晋升总是吃亏怎么办: chapter2/section12.md
        - 2.13 程序员容易最忽略的几件重要的事: chapter2/section13.md
    - 第三章 工作中的人际关系:
        - 概述: chapter3/index.md
        - 3.1 领导一对一（1on1）聊什么: chapter3/section1.md
        - 3.2 领导让我提意见，我该怎么提: chapter3/section2.md
        - 3.3 同事太优秀了，我嫉妒到想退休养猪: chapter3/section3.md
        - 3.4 同事是傻逼，我有厌蠢症，实在受不了了: chapter3/section4.md
        - 3.5 卷王太凶残，我要不要'反卷'？: chapter3/section5.md
        - 3.6 我没有晋升不重要，但是他的晋升让我不爽: chapter3/section6.md
        - 3.7 社恐人混职场是真难啊: chapter3/section7.md
    - 第四章 工作与家庭:
        - 概述: chapter4/index.md
        - 4.1 好的伴侣可以帮你消化工作上的负面情绪: chapter4/section1.md
        - 4.2 维系亲密关系最重要的一点: chapter4/section2.md
        - 4.3 情绪稳定是个伪命题: chapter4/section3.md
        - 4.4 伴侣老是抱怨，我该怎么办: chapter4/section4.md
        - 4.5 婆媳关系真是男人的噩梦啊: chapter4/section5.md
    - 第五章 程序员副业:
        - 概述: chapter5/index.md
        - 5.1 打工人做副业，要先学会转换思维模式: chapter5/section1.md
        - 5.2 2025年程序员最值得做的副业: chapter5/section2.md
        - 5.3 副业跑起来最重要的一点: chapter5/section3.md
        - 5.4 副业中，如何克服畏难情绪: chapter5/section4.md
        - 5.5 如何平衡主业和副业: chapter5/section5.md
    - 第六章 只工作不上班:
        - 概述: chapter6/index.md
        - 6.1 我所接触到的程序员副业: chapter6/section1.md
        - 6.2 gap 无罪，寻找属于你自己的pathless path: chapter6/section2.md
        - 6.3 其实，不工作，也能活得很好: chapter6/section3.md
    - 结语：成为一个自洽的程序员: epilogue.md
    - 法律条款:
        - 服务条款: terms.md
        - 隐私政策: privacy.md
        - Cookie 政策: cookies.md
